### ISSUE TITLE
The project is not being built

### ISSUE THREAD

**Issue by techie-mike** [K3S-prod/k3s-virtual-machine#2]
I started cmake:
```bash
k3s-virtual-machine/$  mkdir build
k3s-virtual-machine/$ cd build
k3s-virtual-machine/build$  cmake ..
```
And got:
```bash
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.16)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/texnar/Documents/programming/huawei/k3s-virtual-machine/build
```
After ran make:
```bash
k3s-virtual-machine/build$ make all
```
And got error:
```bash
[ 16%] Generating generated/lexer.l, generated/grammar.l, generated/opcodes.h
Traceback (most recent call last):
	4: from /home/texnar/Documents/programming/huawei/k3s-virtual-machine/assembler/templates/isa_parser.rb:45:in `<main>'
	3: from /home/texnar/Documents/programming/huawei/k3s-virtual-machine/assembler/templates/isa_parser.rb:45:in `each'
	2: from /home/texnar/Documents/programming/huawei/k3s-virtual-machine/assembler/templates/isa_parser.rb:49:in `block in <main>'
	1: from /home/texnar/Documents/programming/huawei/k3s-virtual-machine/assembler/templates/isa_parser.rb:49:in `open'
/home/texnar/Documents/programming/huawei/k3s-virtual-machine/assembler/templates/isa_parser.rb:49:in `initialize': No such file or directory @ rb_sysopen - /home/texnar/Documents/programming/huawei/k3s-virtual-machine/build/assembler/generated/lexer.l (Errno::ENOENT)
make[2]: *** [assembler/CMakeFiles/assembler.dir/build.make:78: assembler/generated/lexer.l] Error 1
make[1]: *** [CMakeFiles/Makefile2:94: assembler/CMakeFiles/assembler.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

@dkofanov, please, help to fix

**Comment by techie-mike** [comment]
Hmm, I build with `Ninja` and build is successful

**Comment by sin-diesel** [comment]
Solved with https://github.com/K3S-prod/k3s-virtual-machine/pull/3
